-- DEPRECATED: superseded by workshops-instructor-id.sql.
--
-- The previous "any authenticated user can do anything" policies on public.workshops
-- have been replaced by ownership + role-based policies tied to public.profiles.
-- Run supabase/workshops-instructor-id.sql instead. It is idempotent and will drop
-- the old policies before recreating them correctly.
